---
title: "R Notebook"
output: html_notebook
---

#Collect expression of all human kinases
```{r}

data_path<-"/home/fgao/Data_Proteomics/"
human_kinases<-read.table(paste(data_path, "kinmap/list_human_kinases.txt", sep=""), quote="", sep="\t", header=T)

exp_cfz_over_pxn<-read.csv(paste(data_path, "PEL/analysis_20220215/expression-diff_limma_proteins_raw/pxn_cfz_over_pxn_ctrl.csv", sep=""), header = TRUE)
exp_cfz_over_pxn_kinases<-merge(human_kinases, exp_cfz_over_pxn, by.x="UniprotID", by.y="protein_accession")
exp_cfz_over_pxn_kinases_stat<-data.frame(Name=exp_cfz_over_pxn_kinases$Name, 
                                          log2_foldchange=exp_cfz_over_pxn_kinases$log2_foldchange, 
                                          p_value=exp_cfz_over_pxn_kinases$p_value)

exp_cis_over_pxn<-read.csv(paste(data_path, "PEL/analysis_20220215/expression-diff_limma_proteins_raw/pxn_cis_over_pxn_ctrl.csv", sep=""), header = TRUE)
exp_cis_over_pxn_kinases<-merge(human_kinases, exp_cis_over_pxn, by.x="UniprotID", by.y="protein_accession")
exp_cis_over_pxn_kinases_stat<-data.frame(Name=exp_cis_over_pxn_kinases$Name, 
                                          log2_foldchange=exp_cis_over_pxn_kinases$log2_foldchange, 
                                          p_value=exp_cis_over_pxn_kinases$p_value)

exp_ctrl_over_ac<-read.csv(paste(data_path, "PEL/analysis_20220215/expression-diff_limma_proteins_raw/pxn_ctrl_over_ac.csv", sep=""), header = TRUE)
exp_ctrl_over_ac_kinases<-merge(human_kinases, exp_ctrl_over_ac, by.x="UniprotID", by.y="protein_accession")
exp_ctrl_over_ac_kinases_stat<-data.frame(Name=exp_ctrl_over_ac_kinases$Name, 
                                          log2_foldchange=exp_ctrl_over_ac_kinases$log2_foldchange, 
                                          p_value=exp_ctrl_over_ac_kinases$p_value)

write.table(exp_cfz_over_pxn_kinases_stat, file=paste(data_path, "PEL/analysis_20220215/pxn_cfz_over_pxn_ctrl_stat.txt", sep=""), quote=F, sep="\t", row.names=F)
write.table(exp_cis_over_pxn_kinases_stat, file=paste(data_path, "PEL/analysis_20220215/pxn_cis_over_pxn_ctrl_stat.txt", sep=""), quote=F, sep="\t", row.names=F)
write.table(exp_ctrl_over_ac_kinases_stat, file=paste(data_path, "PEL/analysis_20220215/pxn_ctrl_over_ac_stat.txt", sep=""), quote=F, sep="\t", row.names=F)


exp4<-read.csv(paste(data_path, "PEL/analysis_20220907/expression-diff_ttest_proteins_raw/table_expression_limma_cis_pxn_over_ctl.csv", sep=""), header = TRUE)
exp4_kinases<-merge(human_kinases, exp4, by.x="UniprotID", by.y="protein_accession")
exp4_kinases_stat<-data.frame(Name=exp4_kinases$Name, log2_foldchange=exp4_kinases$log2_foldchange, p_value=exp4_kinases$p_value)

exp5<-read.csv(paste(data_path, "PEL/analysis_20220907/expression-diff_ttest_proteins_raw/table_expression_limma_cis_pxn_over_pxn.csv", sep=""), header = TRUE)
exp5_kinases<-merge(human_kinases, exp5, by.x="UniprotID", by.y="protein_accession")
exp5_kinases_stat<-data.frame(Name=exp5_kinases$Name, log2_foldchange=exp5_kinases$log2_foldchange, p_value=exp5_kinases$p_value)

exp6<-read.csv(paste(data_path, "PEL/analysis_20220907/expression-diff_ttest_proteins_raw/table_expression_limma_pxn_over_ctl.csv", sep=""), header = TRUE)
exp6_kinases<-merge(human_kinases, exp6, by.x="UniprotID", by.y="protein_accession")
exp6_kinases_stat<-data.frame(Name=exp6_kinases$Name, log2_foldchange=exp6_kinases$log2_foldchange, p_value=exp6_kinases$p_value)

write.table(exp4_kinases_stat, file=paste(data_path, "PEL/analysis_20220907/cis_pxn_over_ctrl_stat.txt", sep=""), quote=F, sep="\t", row.names=F)
write.table(exp5_kinases_stat, file=paste(data_path, "PEL/analysis_20220907/cis_pxn_over_pxn_stat.txt", sep=""), quote=F, sep="\t", row.names=F)
write.table(exp6_kinases_stat, file=paste(data_path, "PEL/analysis_20220907/pxn_over_ctl_stat.txt", sep=""), quote=F, sep="\t", row.names=F)

```


```{bash}

cd /home/fgao/Data_Proteomics/PEL/analysis_20220907/
awk '{if($2<0 && $3<0.05) print "@0:"(sqrt($2*$2)*20)":blue:black:1.5\n"$1}' cis_pxn_over_ctrl_stat.txt > cis_pxn_over_ctrl_dn.txt
awk '{if($2>0 && $3<0.05) print "@0:"(sqrt($2*$2)*20)":red:black:1.5\n"$1}' cis_pxn_over_ctrl_stat.txt > cis_pxn_over_ctrl_up.txt

awk '{if($2<0 && $3<0.05) print "@0:"(sqrt($2*$2)*20)":blue:black:1.5\n"$1}' cis_pxn_over_pxn_stat.txt > cis_pxn_over_pxn_dn.txt
awk '{if($2>0 && $3<0.05) print "@0:"(sqrt($2*$2)*20)":red:black:1.5\n"$1}' cis_pxn_over_pxn_stat.txt > cis_pxn_over_pxn_up.txt

awk '{if($2<0 && $3<0.05) print "@0:"(sqrt($2*$2)*20)":red:black:1.5\n"$1}' pxn_over_ctl_stat.txt > pxn_over_ctl_up.txt
awk '{if($2>0 && $3<0.05) print "@0:"(sqrt($2*$2)*20)":blue:black:1.5\n"$1}' pxn_over_ctl_stat.txt > pxn_over_ctl_dn.txt

```


#WGCNA network
```{r}

library(WGCNA)
options(stringsAsFactors = FALSE);
allowWGCNAThreads()

data_path<-"/home/fgao/Data_Proteomics/"
exp1<-read.table(paste(data_path, "PXN_interactome1.txt", sep=""), sep="\t", header=T)
exp2<-read.table(paste(data_path, "PXN_interactome2.txt", sep=""), sep="\t", header=T)
exp3<-read.table(paste(data_path, "PXN_interactome3.txt", sep=""), sep="\t", header=T)
exp12<-merge(exp1, exp2, by="Accession")
exp_all<-merge(exp12, exp3, by="Accession")
exp_sel<-exp_all
rownames(exp_sel)<-exp_sel$Accession
exp_sel<-exp_sel[,-c(1,2,11)]

dat<-as.data.frame(t(exp_sel))
names(dat)<-rownames(exp_sel)
rownames(dat)<-names(exp_sel)
# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=30, by=2))
# Call the network topology analysis function and select power with SFT.R.sq>0.8
sft = pickSoftThreshold(dat, powerVector = powers, blockSize=1200, verbose = 3, networkType = "signed")
#power=28

```


```{r}

data_path<-"/home/fgao/Data_Proteomics/"

Adj_dat = adjacency(dat, power = 28, type="signed")
diag(Adj_dat)=0
dissTOM_dat =1-TOMsimilarity(Adj_dat,TOMType="signed")
geneTree_dat = hclust(as.dist(dissTOM_dat),method="average")

tree_dat=cutreeDynamic(dendro=geneTree_dat,distM=dissTOM_dat, method="tree",deepSplit=FALSE,minClusterSize=20,cutHeight=0.99)
moduleColor_dat=labels2colors(tree_dat)

write.table(data.frame(NAME=exp_all$Gene.Symbol.x,color=moduleColor_dat), file=paste(data_path, "moduleColor_dat.txt", sep=""),quote=FALSE,row.names=FALSE,sep="\t")

png(paste(data_path, "dendro_module.png", sep=""), height=480,width=640)
plotDendroAndColors(geneTree_dat,moduleColor_dat,"module color", abHeight=0.99,
  dendroLabels=FALSE,main="Clustering of PXN interactome",hang=0.03,addGuide=TRUE,guideHang=0.05)
dev.off()

save(dissTOM_dat, geneTree_dat, tree_dat, moduleColor_dat, file = paste(data_path, "networkTOM_dat.RData", sep=""))
```


```{r}

MEs1 = moduleEigengenes(dat, moduleColor_dat)$eigengenes
MEs1_ID = data.frame(ID=rownames(dat),MEs1)
write.table(MEs1_ID, file=paste(data_path, "module_eigengenes.txt", sep=""), quote=FALSE, row.names=FALSE,sep="\t")

write.table(data.frame(ID=rownames(dat)[1:18], PXN_CIS=c(rep(0,4), rep(1,2), rep(0,6), rep(1,2), rep(0,4)), PXN_CTL=c(rep(0,6), rep(1,2), rep(0,8), rep(1,2)), PXN_CFZ=c(rep(0,2), rep(1,2), rep(0,14))), file=paste(data_path, "meta_table.txt", sep=""), quote=F, row.names=F, sep="\t")

# Correlation with different traits
MEs1<-read.table(paste(data_path, "module_eigengenes.txt", sep=""), header=T, row.names=1)
meta<-read.table(paste(data_path, "meta_table.txt", sep=""), header=T, row.names=1)
moduleTraitCor = cor(MEs1, meta, use = "p");
moduleTraitPvalue = corPvalueStudent(moduleTraitCor, nrow(meta));

textMatrix = paste(signif(moduleTraitPvalue, 1), "\n(", signif(moduleTraitCor, 2), ")", sep="")
dim(textMatrix) = dim(moduleTraitCor)

png(paste(data_path, "module_trait_priming.png", sep=""), width=600, height=900)
#library(svglite)

#svglite("module_trait_priming.svg", width =6, height=12)
par(mar = c(4, 9, 3, 3));
# Display the correlation values within a heatmap plot
labeledHeatmap(Matrix = moduleTraitCor,
               xLabels = colnames(meta),
               yLabels = names(MEs1),
               ySymbols = names(MEs1),
               colorLabels = FALSE,
               colors = greenWhiteRed(50),
               textMatrix = textMatrix,
               setStdMargins = FALSE,
               cex.text = 1,
               zlim = c(-1,1),
               main = paste("Module-trait relationships"))
dev.off()
```


```{r}
#Gene ontology analysis
moduleColors<-read.table(paste(data_path, "moduleColor_dat.txt", sep=""), header=T, fill=TRUE)
library(gprofiler2)
library(gridExtra)
go_all<-NULL
for (i in unique(moduleColors$color))
        {module_genes<-moduleColors[moduleColors$color%in%i, "NAME"]
         go_module <- gost(query = module_genes,
                organism = "hsapiens", ordered_query = FALSE,
                multi_query = FALSE, significant = TRUE, exclude_iea = FALSE,
                measure_underrepresentation = FALSE, evcodes = FALSE,
                user_threshold = 0.05, correction_method = "bonferroni",
                domain_scope = "annotated", custom_bg = NULL,
                numeric_ns = "", sources = "GO:BP", as_short_link = FALSE)
         go_module_top<-go_module$result[1:10,]
         if(!is.null(go_module_top)) {go_module_top$module<-rep(i, nrow(go_module_top));
                                      go_all <- rbind(go_all, go_module_top);
                                      png(paste("GO_BP_", i, ".png", sep=""),  height = 50*nrow(go_module_top), width = 200*ncol(go_module_top))
                                      grid.table(go_module_top[,c("module", "term_name", "source", "intersection_size", "p_value")])
                                      dev.off();}
        }
#sources = "REAC", "KEGG", "WP", "TF", "HP"
write.table(go_all[,c("module", "term_name", "source", "intersection_size", "p_value")] , file=paste(data_path, "GO_BP_modules.txt", sep=""), quote=F, sep="\t", row.names=F)

go_all<-NULL
for (i in unique(moduleColors$color))
        {module_genes<-moduleColors[moduleColors$color%in%i, "NAME"]
         go_module <- gost(query = module_genes,
                organism = "hsapiens", ordered_query = FALSE,
                multi_query = FALSE, significant = TRUE, exclude_iea = FALSE,
                measure_underrepresentation = FALSE, evcodes = FALSE,
                user_threshold = 0.05, correction_method = "bonferroni",
                domain_scope = "annotated", custom_bg = NULL,
                numeric_ns = "", sources = "WP", as_short_link = FALSE)
         go_module_top<-go_module$result[1:10,]
         if(!is.null(go_module_top)) {go_module_top$module<-rep(i, nrow(go_module_top));
                                      go_all <- rbind(go_all, go_module_top);
                                      png(paste("WP_", i, ".png", sep=""),  height = 50*nrow(go_module_top), width = 200*ncol(go_module_top))
                                      grid.table(go_module_top[,c("module", "term_name", "source", "intersection_size", "p_value")])
                                      dev.off();}
        }
write.table(go_all[,c("module", "term_name", "source", "intersection_size", "p_value")] , file=paste(data_path, "WP_modules.txt", sep=""), quote=F, sep="\t", row.names=F)

go_all<-NULL
for (i in unique(moduleColors$color))
        {module_genes<-moduleColors[moduleColors$color%in%i, "NAME"]
         go_module <- gost(query = module_genes,
                organism = "hsapiens", ordered_query = FALSE,
                multi_query = FALSE, significant = TRUE, exclude_iea = FALSE,
                measure_underrepresentation = FALSE, evcodes = FALSE,
                user_threshold = 0.05, correction_method = "bonferroni",
                domain_scope = "annotated", custom_bg = NULL,
                numeric_ns = "", sources = "KEGG", as_short_link = FALSE)
         go_module_top<-go_module$result[1:10,]
         if(!is.null(go_module_top)) {go_module_top$module<-rep(i, nrow(go_module_top));
                                      go_all <- rbind(go_all, go_module_top);
                                      png(paste("KEGG_", i, ".png", sep=""),  height = 50*nrow(go_module_top), width = 200*ncol(go_module_top))
                                      grid.table(go_module_top[,c("module", "term_name", "source", "intersection_size", "p_value")])
                                      dev.off();}
        }
write.table(go_all[,c("module", "term_name", "source", "intersection_size", "p_value")] , file=paste(data_path, "KEGG_modules.txt", sep=""), quote=F, sep="\t", row.names=F)

```


# Gene Ontology analysis (Over-Representation or GSEA)

```{r}

library(clusterProfiler)

organism = "org.Hs.eg.db"
#BiocManager::install(organism, character.only = TRUE)
library(organism, character.only = TRUE)

```


# Load DEG results from Jeff's data

```{r}

# we want the log2 fold change 
original_gene_list <- exp_cis_over_pxn$log2_foldchange

# name the vector
names(original_gene_list) <- exp_cis_over_pxn$gene_symbol

# omit any NA values 
gene_list<-na.omit(original_gene_list)

# omit any inf values
gene_list <-gene_list[!is.infinite(gene_list)]

# sort the list in decreasing order (required for clusterProfiler)
gene_list = sort(gene_list, decreasing = TRUE)

# Exctract significant results (padj < 0.05)
sig_genes_df = subset(exp_cis_over_pxn, p_value < 0.05)

# From significant results, we want to filter on log2fold change
genes <- sig_genes_df$log2_foldchange

# Name the vector
names(genes) <- sig_genes_df$gene_symbol

# omit NA values
genes <- na.omit(genes)

```


# Over-representative ontology analysis
```{r}


go_enrich <- enrichGO(gene = sig_genes_df$gene_symbol,
                      universe = names(gene_list),
                      OrgDb = organism, 
                      keyType = 'SYMBOL',
                      readable = F,
                      ont = "BP",
                      pvalueCutoff = 0.05, 
                      qvalueCutoff = 0.1)

library(enrichplot)
#upsetplot(go_enrich)

barplot(go_enrich, 
        drop = TRUE, 
        showCategory = 10, 
        title = "GO Biological Pathways",
        font.size = 8)

plotdot1<-dotplot(go_enrich)

plotemap1<-emapplot(go_enrich, showCategory = 10)

plotgo1<-goplot(go_enrich, showCategory = 10)

plotcnet1<-cnetplot(go_enrich, categorySize="pvalue", foldChange=gene_list, showCategory = 10)

plotdot1
plotemap1
plotcnet1

png(paste(data_path, "GO_BP_dep_cis_over_pxn_jeff_dotplot.png", sep=""), width = 1000, height = 400)
plotdot1
dev.off()

png(paste(data_path, "GO_BP_dep_cis_over_pxn_jeff_emapplot.png", sep=""), width = 1000, height = 400)
plotemap1
dev.off()

png(paste(data_path, "GO_BP_dep_cis_over_pxn_jeff_cnetplot.png", sep=""), width = 1000, height = 400)
plotcnet1
dev.off()

```


```{r}

gse2 <- NULL
gse2 <- gseGO(geneList=gene_list, 
             ont ="BP", 
             keyType = "SYMBOL", 
             nPerm = 10000, 
             minGSSize = 3, 
             maxGSSize = 800, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = organism, 
             pAdjustMethod = "none")

plotdot2 <-dotplot(gse2, showCategory=10, split=".sign") + facet_grid(.~.sign)
gse2_pos<-gse2[gse2@result$NES>0, asis=T]
gse2_neg<-gse2[gse2@result$NES<0, asis=T]

plotemap2_pos<-emapplot(gse2_pos, showCategory = 10)
plotemap2_neg<-emapplot(gse2_neg, showCategory = 10)

plotcnet2_pos<-cnetplot(gse2_pos, categorySize="pvalue", foldChange=gene_list, showCategory = 10)
plotcnet2_neg<-cnetplot(gse2_neg, categorySize="pvalue", foldChange=gene_list, showCategory = 10)

plotdot2
plotemap2_pos
plotemap2_neg
plotcnet2_pos
plotcnet2_neg

library(cowplot)
plotemap2<-plot_grid(plotemap2_pos, plotemap2_neg, ncol = 2, align = 'h')
plotcnet2<-plot_grid(plotcnet2_pos, plotcnet2_neg, ncol = 2, align = 'h')

png(paste(data_path, "GO_BP_gsea_cis_over_pxn_jeff_dotplot.png", sep=""), width = 1000, height = 400)
plotdot2
dev.off()

png(paste(data_path, "GO_BP_gsea_cis_over_pxn_jeff_emapplot.png", sep=""), width = 1000, height = 400)
plotemap2
dev.off()

png(paste(data_path, "GO_BP_gsea_cis_over_pxn_jeff_cnetplot.png", sep=""), width = 1000, height = 400)
plotcnet2
dev.off()

```


# Load DEG results from Ting Yu's data

```{r}

# we want the log2 fold change 
original_gene_list <- exp5$log2_foldchange

# name the vector
names(original_gene_list) <- exp5$gene_name

# omit any NA values 
gene_list<-na.omit(original_gene_list)

# omit any inf values
gene_list <-gene_list[!is.infinite(gene_list)]

# sort the list in decreasing order (required for clusterProfiler)
gene_list = sort(gene_list, decreasing = TRUE)

# Exctract significant results (padj < 0.05)
sig_genes_df = subset(exp5, p_value < 0.05)

# From significant results, we want to filter on log2fold change
genes <- sig_genes_df$log2_foldchange

# Name the vector
names(genes) <- sig_genes_df$gene_name

# omit NA values
genes <- na.omit(genes)

```


# Over-representative ontology analysis
```{r}


go_enrich <- enrichGO(gene = sig_genes_df$gene_name,
                      universe = names(gene_list),
                      OrgDb = organism, 
                      keyType = 'SYMBOL',
                      readable = F,
                      ont = "BP",
                      pvalueCutoff = 0.05, 
                      qvalueCutoff = 0.1)

library(enrichplot)
#upsetplot(go_enrich)

barplot(go_enrich, 
        drop = TRUE, 
        showCategory = 10, 
        title = "GO Biological Pathways",
        font.size = 8)

plotdot1<-dotplot(go_enrich)

plotemap1<-emapplot(go_enrich, showCategory = 10)

plotgo1<-goplot(go_enrich, showCategory = 10)

plotcnet1<-cnetplot(go_enrich, categorySize="pvalue", foldChange=gene_list, showCategory = 10)

plotdot1
plotemap1
plotcnet1

png(paste(data_path, "GO_BP_dep_cis_over_pxn_tingyu_dotplot.png", sep=""), width = 1000, height = 400)
plotdot1
dev.off()

png(paste(data_path, "GO_BP_dep_cis_over_pxn_tingyu_emapplot.png", sep=""), width = 1000, height = 400)
plotemap1
dev.off()

png(paste(data_path, "GO_BP_dep_cis_over_pxn_tingyu_cnetplot.png", sep=""), width = 1000, height = 400)
plotcnet1
dev.off()

```


```{r}

gse2 <- NULL
gse2 <- gseGO(geneList=gene_list, 
             ont ="BP", 
             keyType = "SYMBOL", 
             nPerm = 10000, 
             minGSSize = 3, 
             maxGSSize = 800, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = organism, 
             pAdjustMethod = "none")

plotdot2 <-dotplot(gse2, showCategory=10, split=".sign") + facet_grid(.~.sign)
gse2_pos<-gse2[gse2@result$NES>0, asis=T]
gse2_neg<-gse2[gse2@result$NES<0, asis=T]

plotemap2_pos<-emapplot(gse2_pos, showCategory = 10)
plotemap2_neg<-emapplot(gse2_neg, showCategory = 10)

plotcnet2_pos<-cnetplot(gse2_pos, categorySize="pvalue", foldChange=gene_list, showCategory = 10)
plotcnet2_neg<-cnetplot(gse2_neg, categorySize="pvalue", foldChange=gene_list, showCategory = 10)

plotdot2
plotemap2_pos
plotemap2_neg
plotcnet2_pos
plotcnet2_neg

library(cowplot)
plotemap2<-plot_grid(plotemap2_pos, plotemap2_neg, ncol = 2, align = 'h')
plotcnet2<-plot_grid(plotcnet2_pos, plotcnet2_neg, ncol = 2, align = 'h')

png(paste(data_path, "GO_BP_gsea_cis_over_pxn_tingyu_dotplot.png", sep=""), width = 1000, height = 400)
plotdot2
dev.off()

png(paste(data_path, "GO_BP_gsea_cis_over_pxn_tingyu_emapplot.png", sep=""), width = 1000, height = 400)
plotemap2
dev.off()

png(paste(data_path, "GO_BP_gsea_cis_over_pxn_tingyu_cnetplot.png", sep=""), width = 1000, height = 400)
plotcnet2
dev.off()

```


#Enrichment of Kinases in protein modules 
```{r}

exp_all_kinases<-merge(exp_all, human_kinases, by.x="Accession", by.y="UniprotID", all.x=TRUE)

kinases_modules<-overlapTable(moduleColor_dat, exp_all_kinases$Group, na.rm = TRUE)

kinases_logp<-(-log10(kinases_modules$pTable))

png(paste(data_path, "module_kinase_type.png", sep=""), width=600, height=600)
par(mar = c(6, 6, 6, 6));
# Display the correlation values within a heatmap plot
labeledHeatmap(Matrix = kinases_logp,
               xLabels = colnames(kinases_logp),
               yLabels = paste("ME", rownames(kinases_logp), sep=""),
               ySymbols = paste("ME", rownames(kinases_logp), sep=""),
               colorLabels = FALSE,
               colors = greenWhiteRed(100)[50:100],
               setStdMargins = FALSE,
               cex.text = 1,
               zlim = c(0,2),
               main = paste("Enrichment of kinases in modules"))
dev.off()

```

